apiVersion: apps/v1
kind: Deployment
metadata:
  name: cit270josueservice
spec:
  replicas: 1
  selector: 
    matchLabels:
      app: cit270josueservice
  template:
    metadata:
      name: cit270josueservice
      labels:
        app: cit270josueservice
    spec:
      containers:
      - name: cit270josueservice
        image: gcr.io/mythic-producer-379820/josue-api
        volumeMounts:
        - name: ssl
          mountPath: "/etc/letsencrypt/live/josueavila.cit270.com/"
        command: ["npm"]
        args: ["run", "start"]
        resources:
          requests:
            cpu: "0.125"
            memory: 500Mi
          limits:
            cpu: "0.125"
            memory: 600Mi
        imagePullPolicy: Always
      volumes:
      - name: ssl
        secret:
          secretName: josuecerts
---
apiVersion: v1
kind: Service
metadata: 
  name: stedi-josueavila-nodeport
spec: 
  selector: 
    app: cit270josueservice
  type: NodePort
  ports:
    - port: 80
      targetPort: 3000
---
apiVersion: networking.gke.io/v1
kind: ManagedCertificate
metadata:
  name: stedi-josueavila-certificate2
spec:
  domains:
    - josueavila.cit270.com
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: stedi-josueavila-ingress
  annotations:
    kubernetes.io/ingress.global-static-ip-name: cit270josue
    networking.gke.io/managed-certificates: stedi-josueavila-certificate2
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend: 
          service:
            name: stedi-josueavila-nodeport
            port:
              number: 80