apiVersion: apps/v1
kind: Deployment
metadata:
  name: cit270josueservice
spec:
  replicas: 1
  selector: 
    matchLabels:
      app: cit270josueservice
  template:
    metadata:
      name: cit270josueservice
      labels:
        app: cit270josueservice
    spec:
      containers:
      - name: cit270josueservice
        image: gcr.io/mythic-producer-379820/josue-api
        volumeMounts:
        - name: ssl
          mountPath: "/etc/letsencrypt/live/josueavila.cit270.com/"
        command: ["npm"]
        args: ["run", "start"]
        resources:
          requests:
            cpu: "0.125"
            memory: 500Mi
          limits:
            cpu: "0.125"
            memory: 600Mi
        imagePullPolicy: Always
      volumes:
      - name: ssl
        secret:
          secretName: josuecerts
---
